### ISSUE TITLE
Add metadata props for keywords

### ISSUE THREAD

**Issue by sharanagoudapatil** [hlxsites/danaher-ls-aem#150]
Fetch metadata properties of og:type, og:site_name and og:url from page properties

![image](https://github.com/hlxsites/danaher-ls-aem/assets/141244748/c7647932-6ef3-4a6d-a072-2e8ca8326306)

Plus `keywords` are missing as well.

**Comment by mhaack** [comment]
Most of these we don't need to take care of in the converter as the platform will do automatically. og:title & og:description only needed to be added if they are different the title & description.
og:image is only needed if different from the top main image, otherwise we can also skip it in the converter as it gets added on rendering automatically

**Comment by sharanagoudapatil** [comment]
@mhaack - As per your comments, I've updated the metadata for 'keywords' and raised the PR for it. Please have a look. Thanks.
