### ISSUE TITLE
[Products] Implement base product detail block based on Coveo

### ISSUE THREAD

**Issue by mhaack** [hlxsites/danaher-ls-aem#164]
Implement base product detail block connecting to Coveo as data source.

![Screenshot 2023-09-29 at 13 54 16](https://github.com/hlxsites/danaher-ls-aem/assets/2643450/cdc2c6de-d7ea-4ae4-833b-eb9a2de02f37)

- [ ] Implement connection to Coveo
- [ ] Style product details

**Comment by davidzochowski** [comment]
Just a note, the meta title and meta description will be coming from Coveo so when implementing the Product page, we need to account for this.

**Comment by mhaack** [comment]
@davidzochowski @dave-nichols this is something we need to look into ☝️ . @davidzochowski in today's AEM page I understood parts of the PDP coveo data is server side rendered while some others are client side.

**Comment by davidzochowski** [comment]
@mhaack Correct, the Product Page is rendered from a combination of serverside and clientside calls.
Server side:
This is where the Main information for the Product Page comes from (images, title, description, etc). This used to be clientside however a requirement came in to populate the og metadata within the <head> so this call had to be moved serverside in order to do that. The same thing will happen for the meta title and meta description for next AEM release.
This information is also populating the content for the Overview Tab and Specifications Tab.
This will also determine the appearance of the Product and Resources Tab but not the content.
A product will have a integer field "numproducts" and "numresources" and if these values are > 0, then the tabs will show.

Client side:
When a user clicks on the Product or Resources Tab, then a call is made to Coveo to fetch the assigned Products/Documents and render them to the user.

**Comment by davidzochowski** [comment]
You can go here to see an example of a Family that has both tabs.
https://dev.lifesciences.danaher.com/us/en/products/family/allegra-v-15r-benchtop-centrifuges-beckman-coulter-life-sciences.html

**Comment by davenichols-DHLS** [comment]
@rgravitvl  - as discussed, this is now a duplicate to your task.
