### ISSUE TITLE
Non-Index the Fragment pages

### ISSUE THREAD

**Issue by davenichols-DHLS** [hlxsites/danaher-ls-aem#174]
Currently these are indexed and Google is picking them up, can we mark these as no-index

Example:  https://lifesciences.danaher.com/fragments/wesee.html

**Comment by mhaack** [comment]
@duynguyen I think this is picked up because we have it in the content as `<a href="[/fragments/wesee.html](https://lifesciences.danaher.com/fragments/wesee.html)">WeSee</a>` hence interpret as normal link. We need to remove it from the doc and only have an empty `wesee` block which has the link hard coded.

**Comment by duynguyen** [comment]
@mhaack I think this is fixed already. can we close?
