### ISSUE TITLE
[Research] How do we publish header and footer

### ISSUE THREAD

**Issue by mhaack** [hlxsites/danaher-ls-aem#4]
Today's AEM page header and footer are AEM experience fragments. How can we publish these as well and render via the transformer.

This has impact on the subscriber as well as it must "listen" to these URLs as well.

Additionally todays top menu is already (partially) available via JSON. So either we can just load this JSON in the header block, should be fast as cached be the CDN, does not matter if delivered from AEM publish. Or we publish it to Franklin as well, either as JSON or header HTML fragment.

**Comment by tmaret** [comment]
> This has impact on the subscriber as well as it must "listen" to these URLs as well.

Challenge is the fact that the list of paths to be exported to Franklin is dynamic and thus can't be configured ? I may lack some context.

**Comment by mhaack** [comment]
I think this can be a fixed set off URLs/paths at the beginning. Lets sync with the DH team for a final list at the moment I see following 3 paths:

- landing page
- XF for header
- XF for footer

**Comment by Buuhuu** [comment]
Initially we thought we use a context aware configuration to link AEM to a a GitHub project and hence a Franklin domain (Owner/Repo/Branch). This configuration could be applied to both Sites and Experience Fragments. It will also be used to load the scripts/styles when editing a Franklin site in UE in the future. 

One more thing that counts here is the path mapping. When publishing `/content/danaher/ls/us/en` the subscriber should actually POST to `https://admin.hlx.page/preview/owner/repo/main/index` when the CA config is set at `/content/danaher/ls/us/en`. If it would be set on `/content/danaher/ls/us` instead it should POST to `https://admin.hlx.page/preview/owner/repo/main/en`. The converter must than be able to again resolve the correct path. This is due to the fact that franklin does not support path mappings intentionally.

**Comment by mhaack** [comment]
Update on the header mega menu part (via JSON today): as the JSON is static we will fetch the JSON during the conversion and transform/embed a mapped HTML structure for the mega menu already in the header. (cc: @bpauli)

**Comment by mhaack** [comment]
Closing this one as we have it already implemented.
