### ISSUE TITLE
[Product Home] Product Spotlight Two column control UX/UI

### ISSUE THREAD

**Issue by davenichols-DHLS** [hlxsites/danaher-ls-aem#509]
Product Spotlight block

![image](https://github.com/hlxsites/danaher-ls-aem/assets/124819426/614fb70d-52bd-4afd-aa1b-1351fe0b6002)

https://www.figma.com/file/fgBV6T1rkYBvzQYzwwUnFt/Bioscience-hub-3?type=design&node-id=19011-234971&mode=design&t=2kBAcLaUMaXZ90KY-0

**Comment by amlan18041996** [comment]
Kindly refer to following **[MR](https://github.com/hlxsites/danaher-ls-aem/pull/561)** for the layout of `PRODUCT SPOTLIGHT` as discussed. Kindly let me know if we have to create a separate component or any further changes required.

**Discussed Points:**
- Based on figma design, it was concluded that the layout-structure of `product-spotlight` & carousel-slides are identical.
- Due to the default behaviour of carousel, only the first slide will be shown with `no-navigation` & `no-pagination` & `no-transition` if in any case there is only one slide available; which resulting in showing the structure of `product-spotlight`.

**Comment by davenichols-DHLS** [comment]
Thanks @amlan18041996  - I am checking this out.  I noticed one small issue that I think might be authoring, the spotlight first button is blank

![image](https://github.com/hlxsites/danaher-ls-aem/assets/124819426/a4843ce2-5ab3-44f8-893a-5ff5d2fca6bc)
